Optical changes and var translation
UnknownEdgar/Schiffe_Versenken pull request #9
Opened 2024-03-14 13:41 UTC by johannesrdph

2024-03-14 16:04 UTC, glutto-3001 approved these changes
nicely done!

2024-03-15 10:52 UTC, UnknownEdgar requested changes
nicht einheitlich in den Unterpunkten

2024-03-16 16:48 UTC, UnknownEdgar approved these changes

2024-03-16 16:50 UTC, glutto-3001 approved these changes

2024-03-16 16:51 UTC, merged